language: C

before_install:
  - "sudo apt-get update"

install:
  # Prerequisites
  - "sudo apt-get install autotools-dev debhelper gobjc gobjc-multilib libgnustep-base-dev gnustep-core-devel sqlite libsqlite3-dev openssl libcurl4-openssl-dev curl tcl tcl-dev tcl-doc tclthread tclreadline freebsd-buildutils binutils libc6-dev perl doxygen cvs ed pax"

# make sure mtree installed by freebsd-buildutils is in path, then check env
before_script: export PATH=${PATH}:/usr/lib/freebsd && env | uniq | sort | uniq

# Just try to build first
script: ./configure --with-objc-runtime=GNU --with-objc-foundation=GNU --enable-maintainer-mode --enable-symbols --enable-readline && make

compiler:
  - clang
  - gcc

# Only run tests after success
after_success: pwd && make test
