language: C

before_install:
  - "sudo apt-get update"

install:
  # Prerequisites
  - "sudo apt-get install autotools-dev debhelper gobjc curl libgnustep-base-dev sqlite openssl tclthread freebsd-buildutils tclreadline binutils tcl tcl-dev libc6-dev gnustep-core-devel libsqlite3-dev libcurl4-openssl-dev perl doxygen swig2.0 cvs ed pax rlwrap"

# check env
before_script: export PATH=${PATH}:/usr/lib/freebsd && env | uniq | sort | uniq

# try to build && test
script: ./configure --with-objc-runtime=GNU --with-objc-foundation=GNU --enable-maintainer-mode --enable-symbols --enable-readline && make

compiler:
  - clang
  - gcc

after_success: pwd && make test
