name: cooljeanius/MacPorts-fork
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: sudo apt-get update
    - run: sudo apt-get install autotools-dev debhelper gobjc gobjc++ gobjc-multilib gobjc++-multilib gobjc-9 libgnustep-base-dev gnustep-core-devel sqlite libsqlite3-dev openssl libcurl4-openssl-dev curl tcl tcl-dev tcl-doc tclthread tclreadline mtree-netbsd binutils libc6-dev perl doxygen swig cvs ed pax rlwrap gobjc-9-multilib bmake pmake bzr tcldoc xattr libc-devtools mlocate plocate clang gnustep gnustep-devel gnustep-examples libasprintf-dev libgettextpo-dev steptalk libdbuskit-dev libgorm-dev libpantomime-dev libperformance-dev libpopplerkit-dev libpreferencepanes-dev libsqlclient-dev libsteptalk-dev libnetclasses-dev libaddresses-dev libaddressview-dev librsskit-dev gnustep-dl2 libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev
    - run: (if test -d /usr/lib/freebsd; then export PATH=${PATH}:/usr/lib/freebsd; else locate /usr/lib/freebsd; fi) && env | uniq | sort | uniq
    - run: "./configure --with-objc-runtime=GNU --with-objc-foundation=GNU --enable-maintainer-mode --enable-symbols --enable-readline && make"
    - run: pwd && make test
      if: "${{ success() }}"
    - run: if test -r config.log; then cat config.log && wc -l config.log; elif test -e config.log; then stat config.log; else ls -AR; fi; (echo "looking for objc/objc-api.h..." && (locate objc/objc-api.h || find objc/objc-api.h || echo "not found!")); sleep 3
      if: "${{ failure() }}"
    strategy:
      matrix:
        compiler:
        - clang
        - gcc
